drop table users cascade;
drop table items cascade;

CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS identity not null PRIMARY KEY,
name varchar(255) not null,
email varchar(512) not null unique
);


CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    request_id BIGINT
);
