drop table users cascade;
drop table items cascade;
drop table bookings cascade;

CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS identity not null PRIMARY KEY,
name varchar(255) not null,
email varchar(512) not null unique
);


CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    request_id BIGINT
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items(id),
  booker_id BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(20) NOT NULL,
  CHECK (end_date > start_date)
);

